# application.yml

# 🚀 Configurações do Servidor Web
server:
  port: 8080 # Porta padrão para a sua API

# 🗄️ Configurações do Banco de Dados H2
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # Banco em memória, não fecha após uso
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true        # Habilita o console do H2 para acesso via browser
      path: /h2-console    # URL para acessar o console do H2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update     # Atualiza automaticamente o schema do banco (NÃO usar em produção)
    show-sql: true         # Exibe as queries SQL no console para debug
    properties:
      hibernate:
        format_sql: true   # Formata o SQL exibido para melhor legibilidade

  devtools:
    restart:
      enabled: true        # Reinicia automaticamente a aplicação ao detectar mudanças
    livereload:
      enabled: true        # Ativa LiveReload (necessita extensão no navegador)

# 🔒 Configurações JWT para geração e validação de tokens
jwt:
  secret: umaChaveSecretaMuitoLongaEComplexaParaAssinarTokensJWT
  expiration: 3600000    # Expiração do token em milissegundos (1 hora)

# 📚 Configuração do Springdoc OpenAPI para documentação Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true # Desabilita a URL default para evitar página Petstore
  api-docs:
    path: /v3/api-docs

# ⚠️ Segurança: Caso precise liberar frame options para H2 console (gerenciado via SecurityConfig)
# spring:
#   security:
#     headers:
#       frame-options: sameorigin

